### ISSUE TITLE
Content on new post cleared on orientation change.

### ISSUE THREAD

**Issue by maddler** [Decad3nce/trunks-public#107]
Changing device orientation while writing a new post will cause the entered content to be cleared.

Steps to reproduce:

1. Click on the new post icon
2. Start writing new post
3. Change decice orientation

Current outcome: type text/content disappears
Expected outcome: content to be retained

Comments: could this be related to #92 ? With window content being refreshed on rotation?

App version: 1.1.5
Device: 1+ 10 Pro
OS Version: Android 13

**Comment by tcely** [comment]
It also loses my partially composed posts instead of saving a draft if I open enough other apps on Android.
