### ISSUE TITLE
Bug: Google Play and Mastodon Posts link to interesting page on https://trunks.social 

### ISSUE THREAD

**Issue by jeffsikes** [Decad3nce/trunks-public#126]
In [Google Play](https://play.google.com/store/apps/details?id=com.decad3nce.trunks) the official app link goes to https://trunks.social, which then displays this message. 

![Screenshot 2023-04-03 at 10 27 26 PM](https://user-images.githubusercontent.com/6627582/229685841-a2443ecf-1dad-42b9-97f5-e75eaaba68f5.png)

In addition, if you post using the Trunks app (I assume using the web version, too), it gets tagged as being posted from Trunks (this only displays on your local timeline, I think). It links to the same place as well. 

<img width="889" alt="Screenshot 2023-04-03 at 11 01 24 PM" src="https://user-images.githubusercontent.com/6627582/229684810-659aa4b5-cea3-42f0-ac57-93a0e139bb80.png">

Here's a portion of my status that is returned from a post I created using Trunks Web.

```
  "application": {
    "name": "trunks.social",
    "website": "https://trunks.social"
  },
```

Since the URL goes to "Why are you here?", well, I thought I'd let you know! 😄 

Thought you might want to update the link to go to the GitHub Repo or your Mastodon account while it's still in development. I'm sure I'm not the only one that clicks these links when I find interesting new app names.

Great app, there's some really excellent UI designs and I often open the app just to see your take on existing Mastodon concepts. 🏆

**Comment by Decad3nce** [comment]
I'm planning on pushing out a beta to trunks.social shortly for the website.

**Comment by Decad3nce** [comment]
This is now fixed :)
