### ISSUE TITLE
Flashing 

### ISSUE THREAD

**Issue by rtprio** [Decad3nce/trunks-public#13]
I'm not sure how to describe the issue. There is crazy flashing on nearly every screen.

Nexus 7 / Android 11

https://user-images.githubusercontent.com/901685/215341207-e6435e77-495c-464a-8635-50a6a190cda2.mp4

**Comment by Decad3nce** [comment]
Woah, I'm not even sure where to start with that - Im guessing there's some graphics/rendering issues here with flutter.

**Comment by rtprio** [comment]
Let me know if I can help in any way; I'm not an android developer but have
slight familiarity with the debugging menu.

But I love the layout and look of the app, I can't wait to use it more.

**Comment by Decad3nce** [comment]
@rtprio This may be resolved now with updates in flutter LMK

**Comment by Decad3nce** [comment]
Closing as stale
