### ISSUE TITLE
preview images stretched vertically 

### ISSUE THREAD

**Issue by kocher** [Decad3nce/trunks-public#148]
I am on Android App 1.2.0:104

Some (not all) of the preview images in the timeline are stretched vertically, resulting in people having egg shaped heads.

**Comment by kocher** [comment]
Hi, whats the target release for this fix? 
It's not fixed for me yet in 1.2.0:107. 

Thanks! Keep up the good work.

**Comment by Decad3nce** [comment]
Hey @kocher do you have a reliable repro for this? Maybe a link to a post? I'm struggling to reproduce this with my latest changes.

**Comment by kocher** [comment]
Hey @Decad3nce,

Sure, on this account there are a couple of images with this problem: @derStandard@derstandard.at

![Screenshot_20230527-061136](https://github.com/Decad3nce/trunks-public/assets/5782527/45d90441-5515-4b81-b173-9804adb00534)

**Comment by kocher** [comment]
This also happens with the iOS app, tested on my old iPhone 6s.

**Comment by Decad3nce** [comment]
Appreciate the links.

**Comment by kocher** [comment]
Can confirm this is fixed with 1.2.1:113

Thanks a lot!
