### ISSUE TITLE
[Android] Image/Gif Insertion

### ISSUE THREAD

**Issue by Decad3nce** [Decad3nce/trunks-public#17]
Social keyboards are very common, need to support insertion from the keyboards into compose pages throught the content apis for each platform.

**Comment by Decad3nce** [comment]
https://github.com/flutter/flutter/pull/110052

**Comment by pacorob** [comment]
I hope the option to add a GIF in a post will be added. 

The above description in regards to the social keyboards is I think related to another request to have the # and @ appearing above a post creation (next to e.g. language of the post, poll and such). 

Hope to see both supported in a future release.

**Comment by pacorob** [comment]
I think the social keyboard description needs to be moved from here see also [here](https://github.com/Decad3nce/trunks-public/issues/71)) since it applies to adding the Giphy API to add a GIF to a post easily in e.g. the iOS/iPadOS client.
