### ISSUE TITLE
Post fails to display on Android

### ISSUE THREAD

**Issue by Tortel** [Decad3nce/trunks-public#177]
This post: https://trunks.social/status/androiddev.social/@plaguepoems@mastodon.social/110476649004651088

Fails to load on the Android app - instead it just displays as a giant grey box that you can't scroll past.
Screenshot:
![Screenshot_20230602-175449_trunks](https://github.com/Decad3nce/trunks-public/assets/754980/df089d4c-8955-44ac-a849-26a73d7f441f)

**Comment by Tortel** [comment]
Oh, this is on a Pixel 6 running Android 13

**Comment by Decad3nce** [comment]
Hey friend :)

Thanks for the report. Fixed.
