### ISSUE TITLE
The 1 at alerts is not removed

### ISSUE THREAD

**Issue by FloGamerMC** [Decad3nce/trunks-public#178]
In alerts I have an poll. I tried to click it But the 1 isn't removed. Am I doing something wrong or is this a bug?![image](https://github.com/Decad3nce/trunks-public/assets/70540298/cf8b1c41-fcfd-4744-b01d-70a3ecf2318b)

**Comment by Decad3nce** [comment]
You have to click the double check mark button to mark notifications as read.

I'll make that text more obvious.

**Comment by FloGamerMC** [comment]
Oh I was blind 😂
