### ISSUE TITLE
Android: Favorites Badge number not updating correctly

### ISSUE THREAD

**Issue by wem1c** [Decad3nce/trunks-public#179]
## Description
Tapping on the "Favorite" button on a post in your timeline doesn't always update the count by adding/subtracting one.

Behaviour is irregular - sometimes it won't update the count at all, sometimes it will.

## Video
[imgur - GIF](https://imgur.com/a/zQVj5kh)

## Device info
**model:** Xiaomi Poco F3
**rom:** MIUI Global 14.0.4

**Comment by Decad3nce** [comment]
Duping to #163
