### ISSUE TITLE
Bug: Failed to translate

### ISSUE THREAD

**Issue by pabloscloud** [Decad3nce/trunks-public#180]
I tried to translate a German post, but it doesn't work ![Screenshot_20230603-191925_trunks.png](https://github.com/Decad3nce/trunks-public/assets/93644977/cb0cbe23-2521-4bee-869a-6977d782df59)

**Comment by Decad3nce** [comment]
Translations are handled by your server so if it is failing, there's not much I can do. You can contact your server admin to see what's happening.

I'll add more description to make sure that's communicate well.

**Comment by pabloscloud** [comment]
> Translations are handled by your server so if it is failing, there's not much I can do. You can contact your server admin to see what's happening.
> 
> I'll add more description to make sure that's communicate well.

Alright, I'll contact my admin

**Comment by Decad3nce** [comment]
Details for that API are here: https://docs.joinmastodon.org/entities/Translation/

**Comment by pabloscloud** [comment]
> Details for that API are here: https://docs.joinmastodon.org/entities/Translation/

Thx
