### ISSUE TITLE
The "pen" icon misaligned 

### ISSUE THREAD

**Issue by cccClyde** [Decad3nce/trunks-public#195]
The "pen" icon on the FAB button is not center aligned. I don't know you guys but it really drives me nuts every time I open Trunk (Android).

![Screenshot_20230608-223813.png](https://github.com/Decad3nce/trunks-public/assets/34314096/c974cedf-6f68-4444-b365-32b7f2632a3a)

**Comment by Decad3nce** [comment]
Fixed, thanks!
