### ISSUE TITLE
Character usage count discrepancy

### ISSUE THREAD

**Issue by andyrak** [Decad3nce/trunks-public#196]
Trunks character limit UI states I'm at 500/500 characters, but an error occurs on publish, stating I'm over the character limit.
![image](https://github.com/Decad3nce/trunks-public/assets/1452019/54f201c3-a9e1-468c-865f-8c2107dd99bf)

Mastodon web client shows that I am at 502/500 characters with the same content.
![image](https://github.com/Decad3nce/trunks-public/assets/1452019/e6d99084-a4ec-476d-b4e7-986d021c7db4)

Full text provided here for debugging purposes if necessary.
```
My existing Kasa smart-switch ecosystem was useless after moving from a modern townhouse to a 60s era home without any neutral wiring. I was grieving over finding new solutions that would work with my current wiring, but also gave me upgradability.

Enter Inovelli https://inovelli.com/. Their Blue Series Smart 2-1 Switch is Zigbee-based, doesn't require a neutral wire, and can be configured to work in single, multi-way, on/off and dimmer modes all in a single model. 

Truly impressed with these!
```

Using iOS client Version 1.2.3 (122) on M1 macOS Sonoma (14.0 Beta/23A5257q).

**Comment by Decad3nce** [comment]
It's because Mastodon counts https://inovelli.com/, which is objectively 21 characters as 23 characters

I'm an idiot for thinking they'd be sane and count urls as 23 characters max, affording for shorter. 

good god.
