### ISSUE TITLE
Links in specific post not opening

### ISSUE THREAD

**Issue by arshadrr** [Decad3nce/trunks-public#198]
While tapping on links works on all posts Ive encountered so far, the first ("podcast with...") and second link ("why programmers...") in this specific post dont open: https://types.pl/@agdakx/110519627063095214

The hashtags and tagged account open fine, and the links open when I view the post in the browser.

I'm on 1.2.3:122 on Android, downloaded from the Playstore.

Thanks for writing Trunks, loving it.

**Comment by Decad3nce** [comment]
Oh interesting, these are embedded links. Should be fairly straightforward.
