### ISSUE TITLE
"links" appearing as a word on the left navigation bar.

### ISSUE THREAD

**Issue by justdaj** [Decad3nce/trunks-public#199]
The word "links" is appearing on the Android client (mobile and tablet).  Not clickable.  I'm not clear on its purpose 

V1.2.3.122
![Screenshot_2023-06-10-21-25-27-67](https://github.com/Decad3nce/trunks-public/assets/5741412/36450078-2588-4a58-be64-c3bba2e386b4)

**Comment by Decad3nce** [comment]
This makes more sense on large screen devices - you can see what that looks like on https://trunks.social -

I'll fix this to make sure it doesn't look bad on mobile landscape views.
