### ISSUE TITLE
Mod notifications get shown incorrectly

### ISSUE THREAD

**Issue by do-m-inik** [Decad3nce/trunks-public#200]
If someone registers or if a report was given this is how the notifications look like for mods on the instance on trunks.social.

But I would also thank for that the notifications are at least get shown and not like in other apps are not even getting displayed. That makes moderating easier. 😀 

Version: 1.2.3
iOS version: 16.5
Device: iPhone 12 Mini

![image](https://github.com/Decad3nce/trunks-public/assets/94101596/6db29e10-3660-4ea1-88a2-a8651e0dccfc)

**Comment by Decad3nce** [comment]
Just fixed this in #194

Thanks for the report!

It'll be available in 1.2.4 which is just now rolling out to beta.
