### ISSUE TITLE
Feature Request: Copy Link to Original Post

### ISSUE THREAD

**Issue by justdaj** [Decad3nce/trunks-public#201]
The "Copy Trunks link" is nice, but if you send it to someone else they can't interact.  

It would be nice to be able to quick get the original link too.  At the moment I have to "open on..." then copy the URL in the new window.

We need a quick way for people to follow/interact with the a post sent via email or Fediverse

**Comment by Decad3nce** [comment]
Convice them to use trunks :P 

You should be able to do this by clicking the share icon right now in mobile. That's why I removed it from the overflow.

I added it to the buttons for web for 1.2.5 now.
