### ISSUE TITLE
Can't open some profiles

### ISSUE THREAD

**Issue by Decad3nce** [Decad3nce/trunks-public#207]
humble@birdsite.miisu.net is an example.

**Comment by LewieKong** [comment]
I seem to be having this issue with Calckey domains/accounts. The profile hangs, then I get quasi-signed out of Trunks and have to log back in/reauthenticate again.

I'm on Android 13, using a Samsung Galaxy S21 Ultra and on the most current beta version (1.2.4:125) of Trunks
