### ISSUE TITLE
Show Action Updates toggle does nothing

### ISSUE THREAD

**Issue by Drewdansha** [Decad3nce/trunks-public#212]
Build: 1.2.4:125
Device: Samsung S20+
Software: Android 13

Unless I misunderstand the feature, toggling the "Show Action Updates" in the settings is supposed to not show the action messages that show up at the bottom of the screen (e.g. "Marking notifications as read", "Marked notifications", etc.). No matter if it is on or off, those action notifications still show up. 

Turning that setting off should disable all of those notifications. If those are not the notifications that should be hidden by this feature, then I would like to request that those messages are also able be turned off.

**Comment by Decad3nce** [comment]
I disabled the alerts one, but some of the other ones do actually provide benefit for status updates and are fairly necessary.
