### ISSUE TITLE
Unable to view profiles from Calckey or Kbin/Lemmy

### ISSUE THREAD

**Issue by justdaj** [Decad3nce/trunks-public#214]
When I click on a profile in the time line which is a Calckey or Kbin, a blank pages opens with the spinning blue 'wait' circle.  It never resolves.

Tried it on Web 1.2.4:125 and Android: 1.2.4. 

In Android, the app also logs me out and I have to reauthorise my profile with Trunks

**Comment by Decad3nce** [comment]
Fixed in #207

**Comment by justdaj** [comment]
Sorry, I did check if it had already been logged.  But only the Open issues.  Next time I will look in closed too. 😆
