### ISSUE TITLE
Replies not displaying on

### ISSUE THREAD

**Issue by ThePdog** [Decad3nce/trunks-public#3]
I was trying to access comments/replies to a toot. The link is https://mastodon.au/@LifeTimeCooking/109770408870801950

It appears there is a problem with the mastodon.au instance as I had no difficulties accessing comments/replies on a variety of other instances.

**Comment by Decad3nce** [comment]
I was able to access this locally by dropping the url in the search field of the app. What instance are you access this on? It might be an issue with the instance itself.

**Comment by ThePdog** [comment]
I'm on mas.to, using Moto 5G Stylus android. It was a weird situation as
every other post showed comments. Makes sense it may be tied to instances.
Appreciate you taking a look at it.

Best,

Mike
