### ISSUE TITLE
Lists, Followed Tags, and Instances available in top level navigation

### ISSUE THREAD

**Issue by Decad3nce** [Decad3nce/trunks-public#30]

**Comment by Decad3nce** [comment]
Users should be able to 'pin' any of their favorite lists/tags/instances so that it's more easily available.

**Comment by pacorob** [comment]
It would be great if it would be possible to indeed to have the option to e.g. instead of federated, local, search icon by e.g. long pressing on it to switch between them to see the overview of my lists / overview of followed hashtags or read other other instances in the footer in the iOS app.
