### ISSUE TITLE
Dynamic number of columns on desktop/web

### ISSUE THREAD

**Issue by maddler** [Decad3nce/trunks-public#35]
I want to be able to configure the number of columns or, given the column width, to automatically increase the number of columns if space available. This might make better use of screen estate on bigger screens.

Thanks.
W.

**Comment by pacorob** [comment]
It would be great if multiple columns could also be supported on tablets such as iPadOS and also offer this option for 10inch models to e.g. show timeline, followed hashtag or list and messages in 3 columns side by side.

**Comment by Decad3nce** [comment]
This was actually implemented already.
