### ISSUE TITLE
Where is the actual repo... Codeberg?

### ISSUE THREAD

**Issue by tallship** [Decad3nce/trunks-public#4]
I looked over at Codeberg but no joy. Where is the actual repo? I gave your post a boost from Takahē, which came from a Fediverse address at a mastopub server,  but when I visited https://Trunks.Social it just looped me back to that same Fediverse server address.

I noted multi-account, "Quote Posts", edits, and a couple of other necessary items, but what about scheduling or local only post support, multiple text formats, character count wheels based on server config, link previews in threads, etc.?

Lots of questions 🙂

Does your client support multiple link previews and federating groups like Cakckey does, large previews like SoapBox, Pleroma, and Akkoma, direct subscriptions with Mitra, or direct image imbeds when using Friendica?

Other than those main social Fediverse servers, do you have native support for Pixelfed and PeerTube like Fedilab? What about federating events like what Soapbox and Mobilizon incorporate?

If we're going to do a write up like we just published [here for Relatica](https://write.as/tallship/relatica-the-new-desktop-and-mobile-fediverse-client), or a complete review of your product; a bit more to go on and a code review is a given. You had a beta reference to a Google property, but nothing with regards to F-Droid or a repo (there's no License for this project yet either).

If this is just going to be yet another spin of a retooled Pinafore FE for Fediverse servers as a Android app, then we need to know that, and how it stands out front those others you mentioned - is there native SocialHome or GotoSocial support? There's a demand for that with headless Fediverse server platforms.... Or is this just one of myriad mastopub only alternatives?

We're very interested in advocating for Fediverse FOSS solutions and welcome you and others to share the details of your project with us in the [Fediverse City](https://matrix.to/#/#fediverse-city:matrix.org) Matrix room. We've got s lot of other project developers and users alike.

Even if you've just got a single apk to drop, that would be nice to check it out 🙂 Most FOSSies are somewhat adverse to the Google Playstore and some even Github.

In the meantime I've given you a follow and look forward to your updates!

**Comment by Decad3nce** [comment]
Hey, to be really honest with you, it's going to take some time for me to research all of the different fediverse platforms you've mentioned.

To your note about features, I've updated the issue tracker here with a bit of a roadmap, and it should have some details about what features I'm looking to support.

As for FOSS, apologies but this client and web interface are not open source - maybe they will be in some future. My goal initially was to just make something I'd enjoy using, but its also morphing into something that should be accessible for as many people as possible.

**Comment by KaKi87** [comment]
Hi,

> this client and web interface are not open source - maybe they will be in some future

What's up with that ?

Thanks
