### ISSUE TITLE
White screen after server Auth on Android (firefox)

### ISSUE THREAD

**Issue by tomjowitt** [Decad3nce/trunks-public#5]
After installing the Android client on a Pixel 4 with Android 13, I can log in ok and auth with my instance (hachyderm.io) but the redirect back to the app leaves me on a blank screen state with no options.

I tried force quitting the app but it makes no difference. Screenshot attached.

Looking forward to trying it out and thanks for supporting Android.

![Screenshot_20230129-165324.png](https://user-images.githubusercontent.com/11221/215318352-d99f7819-0bfa-40a9-add1-32587809908d.png)

**Comment by subcalc** [comment]
Same on Galaxy Tab S8 Ultra, Android 13

**Comment by Decad3nce** [comment]
@tomjowitt @subcalc Can either of your provide some more details here?

Default browser? Do you have any modifications?

**Comment by subcalc** [comment]
@Decad3nce was using firefox beta, switched to chrome and it worked

**Comment by Decad3nce** [comment]
Yeah, this seems to be related to firefox beta - please let me know if it also reproduces with the stable branch, if it doesn't, I probably won't bother trying to resolve this on my end.

**Comment by subcalc** [comment]
@Decad3nce I used Firefox stable and Firefox focus. Same white screen.

**Comment by brunelli** [comment]
Also happened to me with Firefox on Android, but it worked when I left the custom tab (three dots -> Open in Firefox).

**Comment by alpha1** [comment]
Same on Samsung s22 with Firefox Stable

**Comment by Decad3nce** [comment]
Unfortunately this seems to be a longstanding firefox issue:

https://bugzilla.mozilla.org/show_bug.cgi?id=1809264

https://alpha.trunks.social/status/@trunksapp/109774356259154467

A bit disappointing, but I'll see what I can do to work around that. It may not be resolved for a bit.

**Comment by tomjowitt** [comment]
Yep, my default is Firefox. I managed to get into the app using @brunelli's suggestion.

**Comment by ellotheth** [comment]
Same on a Moto Edge 30 running Firefox Beta (110.0b4) as the default browser on Android 12. @brunelli's workaround fixed it for me too.

**Comment by gidoca** [comment]
I have that issue too. A workaround that worked for me: instead of pressing authorize in the embedded browser, select open in Firefox from the menu and click authorize from inside Firefox.
