### ISSUE TITLE
Marker support for home feed.

### ISSUE THREAD

**Issue by Decad3nce** [Decad3nce/trunks-public#53]
Keep last position read.

**Comment by pacorob** [comment]
I'm wondering if this means that 1.1.3 includes native sync marker API: https://docs.joinmastodon.org/methods/markers/

See also this conversation: https://alpha.trunks.social/status/mastodon.world/@simonwood@mastodon.social/109862275416110818

**Comment by Decad3nce** [comment]
Yes
