### ISSUE TITLE
Notification banners / Badge on app icon

### ISSUE THREAD

**Issue by pacorob** [Decad3nce/trunks-public#74]
(again) support notification banners and Badge on app icon.
I currently only see notifications when opening in the app at the notifications while Apple Settings > Notifications > trunks > is set correctly to also show them + in Trunks app > Settings > alert settings.

**Comment by Decad3nce** [comment]
Did you enable push notifications?

**Comment by pacorob** [comment]
> Did you enable push notifications?

I sure did both in the app and in Apple notifications settings. 

I noticed last night and this morning again that they now appear sometimes but if they arrive they are much later then another client. In addition it seemed as if they appear when I opened the app, not before it.

**Comment by Decad3nce** [comment]
Unfortunately this is an issue with firebase_messaging in flutter which makes it unnecessarily difficult to handle the case of needing to mutate notifications before displaying them from the client. In trunks case, this is the need to decrypt the notification payload before displaying it.

https://github.com/firebase/flutterfire/discussions/9317

I have some ideas on adressing this, but it likely won't be available for at least another release.
