### ISSUE TITLE
Sharing on Android won't open app in post edit mode.

### ISSUE THREAD

**Issue by maddler** [Decad3nce/trunks-public#83]
This seemsd to be a reoccurrence of #10.
Steps to reproduce:

1. Select content to share
2. Open the share menu and select Trunks

Current result: app opens in "normal" mode
Expected result: app should open in "edit" mode and allow to share content.

Phone: OnePlus 10 pro
OS: Android 13
App version: 1.1.4

**Comment by Decad3nce** [comment]
Can you detail what kind of data it is that you're trying to share? Is it media?

**Comment by maddler** [comment]
Sorry, missed your previous comment.
That would be for any content type actually.
Thanks!
