### ISSUE TITLE
Can't turn push notifications on in android app 

### ISSUE THREAD

**Issue by MarkJR84** [Decad3nce/trunks-public#9]
When I go to turn on push notifications the slider won't stay on. I'll tap it and it'll move to the on position but then immediately turns off again.

I have made sure notifications are turned on for the app in the android system settings.

**Comment by Decad3nce** [comment]
@MarkJR84 Can you provide more details on the phone type, os version, any other customizations you might have?

**Comment by MarkJR84** [comment]
I have a pixel 6 pro running stock android 13. Fully up to date. Not rooted. No customisations.

**Comment by Decad3nce** [comment]
Interesting! Are you able to enable push notifications in any other app? I know of a few instances that don't support push notifications.

**Comment by MarkJR84** [comment]
Yes, I have push notifications in other apps for the instance I have joined.

**Comment by Decad3nce** [comment]
I'm wondering if this is related to the certificate possible failing to generate - can you try clearing the app data and logging back in again?

**Comment by MarkJR84** [comment]
Hi, I cleared the cache and the storage and re signed back in but unfortunately it still doesn't work. 
By the way, thanks for your help on this so far.

**Comment by beckrd** [comment]
Works for me on Samsung S20FE with Android 12.  Maybe a 13 issue?

**Comment by Decad3nce** [comment]
I'm adding a basic debug panel to help narrow this down a bit more in the next release, it'll be in the alert settings page with a 'debug' button in the top corner.
