### ISSUE TITLE
Bug: Profile page links not working everywhere - iOS app

### ISSUE THREAD

**Issue by pacorob** [Decad3nce/trunks-public#97]
On the profile page when checking another user I've noticed that:

- you can't press links (e.g. to a mastodon account) in bio see example: 
-  you can't press on 'posts' in the stats section 

![IMG_2898](https://user-images.githubusercontent.com/122526166/222155935-bcedf50d-76d3-4858-a7ca-9a3ffcf25aad.jpg)

**Comment by Decad3nce** [comment]
Specifically for that account, the referenced '@' reference topics aren't actually links themselves:

Raw html response
```<p>Indie iOS developer in London, UK. Creator of @personalbest.indieapps.space and some other stuff. @shauneba on Twitter. 🏳️‍🌈</p>
```

I'll just make sure I don't highlight anything that isn't a valid link.

**Comment by pacorob** [comment]
Thank you for looking into it and not linking things which aren't link (although in this example they are probably meant as such). I will inform Shaun that his link in his bio don't work this way. I've also tried some other clients and noticed they also weren't linked. 

I hope you can make it possible to press on the 'posts' in stats though.
