### ISSUE TITLE
Quick switch accounts doesn't seem to be working on Android phone

### ISSUE THREAD

**Issue by marekmcg** [Decad3nce/trunks-public#99]
Quick bit of gratitude - *really* like the app, quite possibly best Mastodon on Android already.

Issue:  
The shortcut to quick-switch between accounts is a godsend! It works on Android tablet, but unfortunately not in portrait or landscape mode on Android phone (Samsung A52, Android 13; One UI 5.1).

**Comment by Decad3nce** [comment]
Unfortunately I'm not able to reproduce this locally. Do you have any more details on what happens when you trigger the gesture?

**Comment by marekmcg** [comment]
Ignore, my apologies. This minute an update has come through and it's working as expected, which is excellent! 

Officially my main Mastodon app now. Thanks for this. Have donated to my local refugee support group (Irish Refugee Council).
